trigger: 
- main
pool: Unreal
resources:
  repositories:
    - repository: devops
      type: git
      name: plugins-unreal-publishing
variables: 
- template: variables.yml@devops
steps:
- checkout: devops
- template: azure-pipelines.yml@devops